name: Dotnet Continous Integration

on:
  pull_request:
    branches: [main]

jobs:
  restore_dotnet_tools:
    runs-on: ubuntu-22.04
    steps:
      - name: Go to working directory
        uses: actions/checkout@v3
      - name: Setup Dotnet SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Check directory listing
        run: ls
      - name: Restore dotnet tool
        run: dotnet tool restore
      - name: build all projects using dotnet cake
        run: dotnet cake
      - name: Run dotnet test on test project
        run: dotnet test
