name: Dotnet Continous Integration

on:
  pull_request:
    branches: [main]

jobs:
  restore_dotnet_tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - run: dotnet tool restore
  build_dotnet:
    needs: restore_dotnet_tools
    runs-on: ubuntu-22.04
    steps:
      - run: dotnet cake
  test_dotnet:
    needs: build_dotnet
    runs-on: ubuntu-22.04
    steps:
      - run: dotnet test --project GetGoInterview.Test/GetGoInterview.Test.csproj
